"""Add User model

Revision ID: 6cf3fb1083ca
Revises: ae1e2b305f3d
Create Date: 2025-03-27 22:21:36.930532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf3fb1083ca'
down_revision: Union[str, None] = 'ae1e2b305f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserMusicStat',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('top_Listened_Artist', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('top_Listened_Music', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_UserMusicStat_user_id'), 'UserMusicStat', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserMusicStat_user_id'), table_name='UserMusicStat')
    op.drop_table('UserMusicStat')
    # ### end Alembic commands ###
