"""Add User model

Revision ID: ae1e2b305f3d
Revises: 7e8ed059a3eb
Create Date: 2025-03-27 22:19:16.550795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1e2b305f3d'
down_revision: Union[str, None] = '7e8ed059a3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_certified', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('birthdate', sa.TIMESTAMP(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('accepted_age_gap', sa.Integer(), nullable=False),
    sa.Column('accepted_distance', sa.Integer(), nullable=False),
    sa.Column('targeted_gender', sa.String(), nullable=False),
    sa.Column('favorite_musician', sa.String(), nullable=False),
    sa.Column('favorite_music', sa.String(), nullable=False),
    sa.Column('favorite_musical_style', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_User_user_id'), 'User', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('score_user1', sa.Integer(), nullable=True),
    sa.Column('score_user2', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_feedback_match_id'), 'feedback', ['match_id'], unique=False)
    op.create_table('matche',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('match_compatiblity', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matche_match_id'), 'matche', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matche_match_id'), table_name='matche')
    op.drop_table('matche')
    op.drop_index(op.f('ix_feedback_match_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_User_user_id'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
